## Pandas

### Pandas Series -> it is like a column in a table. It is a 1D array holding data of any type

In [1]:
# importing pandas

import pandas as pd
import numpy as np

#### Series from lists

In [2]:
# string 

country =['India','Russia','USA','Japan']

# makeing series using .series() in pandas
# series has twwo things 1. index, 2. value
pd.Series(country)

0     India
1    Russia
2       USA
3     Japan
dtype: str

In [3]:
# integers

runs = [1,22,30,100,89,99,56,45,34,43]

# creating series
runs = pd.Series(runs)
runs

0      1
1     22
2     30
3    100
4     89
5     99
6     56
7     45
8     34
9     43
dtype: int64

#### custom indexing in series

In [4]:
marks = [90,23,57,34,23]
subject = ['Math','Hindi','English','Science','CS']

# creating series
# now make marks as value and subjects as index
# using index=(jise index banna cahte ho uska name)
marks = pd.Series(marks,index=subject)
marks

Math       90
Hindi      23
English    57
Science    34
CS         23
dtype: int64

#### Setting a name for series objects

In [5]:
# giving a name to this series
# using name parameter
pd.Series(marks,index=subject,name="Rohit's marks")

Math       90
Hindi      23
English    57
Science    34
CS         23
Name: Rohit's marks, dtype: int64

### Series from dictionary

In [6]:
# creating series from dictionary

# dictionary
sub_marks = {
    'math' : 100,
    'english' : 90,
    'science' : 100,
    'history' : 84,
}

In [7]:
# creating series from dictionary
marks_series = pd.Series(sub_marks,name="Mohit's marks")
marks_series

math       100
english     90
science    100
history     84
Name: Mohit's marks, dtype: int64

#### Series Attribute

In [8]:
# size attribute
# this tells us how many items are there in our series

# this will tell us about the size of our series
marks_series.size

4

In [9]:
# dtype
# this will tell us the type of data stored in series

marks_series.dtype

dtype('int64')

In [10]:
# name
# this will tell the name of our siries

marks_series.name

"Mohit's marks"

In [11]:
# is_unique
# this tells that all the items in a series are unique or not 
marks_series.is_unique

False

In [12]:
# index
# this will display all the index value in series

marks_series.index

Index(['math', 'english', 'science', 'history'], dtype='str')

In [13]:
# values
# this gives index object
# this will display all the value present in series

marks_series.values

array([100,  90, 100,  84])

## Series using read_csv

In [14]:
# importing subs.csv
df = pd.read_csv('data/subs.csv')


# creating series
df = df['Subscribers gained']
type(df)

pandas.Series

In [15]:
# reading data from csv file 

# reading kohli_ipl.csv data
kohli_runs = pd.read_csv('data/kohli_ipl.csv')
kohli_runs

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [16]:
# converting kohli_ipl.csv into series 
kohli_series = kohli_runs['runs']
kohli_series

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

In [17]:
# working with bollywood.csv

# reading bollywood.csv
bolly_data = pd.read_csv('data/bollywood.csv')
bolly_data

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [18]:
# making series of movie column
bolly_series = bolly_data['movie']
bolly_series

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1495                  Hum Tumhare Hain Sanam
1496                     Aankhen (2002 film)
1497                         Saathiya (film)
1498                          Company (film)
1499                    Awara Paagal Deewana
Name: movie, Length: 1500, dtype: str

In [19]:
# making series of lead column
bolly_lead_series = bolly_data['lead']
bolly_lead_series

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1495      Shah Rukh Khan
1496    Amitabh Bachchan
1497        Vivek Oberoi
1498          Ajay Devgn
1499        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [20]:
# making lead column -> index 
bolly_data = pd.read_csv('data/bollywood.csv',index_col='lead')
bolly_data

                                                 movie
lead
Vicky Kaushal                 Uri: The Surgical Strike
Vicky Ahuja                              Battalion 609
Anupam Kher       The Accidental Prime Minister (film)
Emraan Hashmi                          Why Cheat India
Mona Ambegaonkar                       Evening Shadows
...                                                ...
Shah Rukh Khan                  Hum Tumhare Hain Sanam
Amitabh Bachchan                   Aankhen (2002 film)
Vivek Oberoi                           Saathiya (film)
Ajay Devgn                              Company (film)
Akshay Kumar                      Awara Paagal Deewana

[1500 rows x 1 columns]

In [21]:
# making movie column -> index 
bolly_data = pd.read_csv('data/bollywood.csv',index_col='movie')
bolly_data

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

## Series Method

#### working with subs.csv data set

In [22]:
# head ->  Returns the first 5 rows of a Series (used for preview of data)
df.head

<bound method NDFrame.head of 0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64>

In [23]:
# tail ->  Returns the last 5 rows of a Series (used for preview of data)
df.tail

# if you want to see specific number of tails use
# df.tail(10) -> this will print last 10 rows of the data

<bound method NDFrame.tail of 0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64>

In [24]:
# sample -> picks up one random row from the data 
df.sample

<bound method NDFrame.sample of 0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64>

#### working with kohli.csv

In [25]:
# head ->  Returns the first 5 rows of a Series (used for preview of data)
kohli_runs.head(10)

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1
5         6     9
6         7    34
7         8     0
8         9    21
9        10     3

In [26]:
# tail ->  Returns the last 5 rows of a Series (used for preview of data)
kohli_runs.tail(10)

# if you want to see specific number of tails use
# kohli_runs.tail(10) -> this will print last 10 rows of the data

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [27]:
# sample
kohli_runs.sample

<bound method NDFrame.sample of      match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]>

In [28]:
# find the highest score of virat kohli

# dataframe
# kohli_runs.sort_values(by='runs',ascending=False)

# series
# sort_values do temporary changes in the series
# this is also the example of method chaining
kohli_series.sort_values(ascending=False)

# if we want to change our original series -> use inplace=True and this will permanently change the series

127    113
125    109
122    108
163    100
119    100
      ...
92       0
210      0
129      0
7        0
134      0
Name: runs, Length: 215, dtype: int64

### Working with bollywood.csv

In [29]:
# head
bolly_data.head(10)

                                                      lead
movie
Uri: The Surgical Strike                     Vicky Kaushal
Battalion 609                                  Vicky Ahuja
The Accidental Prime Minister (film)           Anupam Kher
Why Cheat India                              Emraan Hashmi
Evening Shadows                           Mona Ambegaonkar
Soni (film)                           Geetika Vidya Ohlyan
Fraud Saiyaan                                 Arshad Warsi
Bombairiya                                    Radhika Apte
Manikarnika: The Queen of Jhansi            Kangana Ranaut
Thackeray (film)                       Nawazuddin Siddiqui

In [30]:
# tail
bolly_data.tail(10)

                                        lead
movie
Raaz (2002 film)                  Dino Morea
Zameen (2003 film)                Ajay Devgn
Waisa Bhi Hota Hai Part II      Arshad Warsi
Devdas (2002 Hindi film)      Shah Rukh Khan
Kaante                      Amitabh Bachchan
Hum Tumhare Hain Sanam        Shah Rukh Khan
Aankhen (2002 film)         Amitabh Bachchan
Saathiya (film)                 Vivek Oberoi
Company (film)                    Ajay Devgn
Awara Paagal Deewana            Akshay Kumar

In [31]:
# sample 
bolly_data.sample()

                                 lead
movie
Bachche Kachche Sachche  Manoj Babani

In [32]:
# value_counts -> tells us about the frequency of data 
bolly_data.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [33]:
# sort_index() -> sort all the index in a series
bolly_data.sort_index(ascending=True)

# permanently sorting the index (movie) column using inplace=True
bolly_data.sort_index(inplace=True)
bolly_data

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

## Series Math Methods

In [34]:
# count -> this counts all the total number of items present in a series and it dosen't counts the missing values
kohli_series.count()

np.int64(215)

In [35]:
# sum

# this will do the sum of all the runs made by virat kohli
kohli_runs['runs'].sum()

np.int64(6634)

In [36]:
# product
df.product()

np.int64(0)

### Statistical methods

In [37]:
# mean
df.mean()

np.float64(135.64383561643837)

In [38]:
# median
df.median()

np.float64(123.0)

In [39]:
# find mean of all the runs made by virat kohli
# or we can say this is the average run made by virat kohli
kohli_runs['runs'].mean()

np.float64(30.855813953488372)

In [40]:
# mode
df.mode()

0    105
Name: Subscribers gained, dtype: int64

In [41]:
# mode (frequently occuring score by virat)
kohli_series.mode()

0    0
Name: runs, dtype: int64

In [42]:
# find which actor made most of the movies
# bolly_lead_series() -> actors (lead) column
bolly_lead_series .mode()

0    Akshay Kumar
Name: lead, dtype: str

In [43]:
# std -> it tells how spread out data is
df.std()

np.float64(62.6750230372527)

In [44]:
# var ->
kohli_series.var()

np.float64(688.0024777222343)

In [45]:
# min

# find maximum runs made by virat kohli
kohli_series.max()

np.int64(113)

In [46]:
# min

# find minimum runs made by virat kohli
kohli_series.min()

np.int64(0)

In [47]:
# find minimum number of movies made by actor/actoress
bolly_lead_series.min()

'Aadar Jain'

In [48]:
# describe -> it provies summary of the data

kohli_runs.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [49]:
# describe for bollywood
bolly_data.describe()

                lead
count           1500
unique           566
top     Akshay Kumar
freq              48

In [50]:
# describe for subs
df.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

## Series Indexing

In [51]:
# integer indexing

# creating a series
x =pd.Series([1,2,54,472,45,7,345,235,234])

In [52]:
# indexing 
# positive indexing
# syntax -> series_name[index number]
x[3]

np.int64(472)

In [53]:
# slicing
bolly_series[0]

'Uri: The Surgical Strike'

In [54]:
# slicing
# print the runs made by virat kohli between 5-15 matches
kohli_series[4:15]

4      1
5      9
6     34
7      0
8     21
9      3
10    10
11    38
12     3
13    11
14    50
Name: runs, dtype: int64

In [55]:
# negative slicing 
kohli_series[-5:]

210     0
211    20
212    73
213    25
214     7
Name: runs, dtype: int64

In [56]:
# negative slicing in movies
# las 5 movies
bolly_series[-5:]

1495    Hum Tumhare Hain Sanam
1496       Aankhen (2002 film)
1497           Saathiya (film)
1498            Company (film)
1499      Awara Paagal Deewana
Name: movie, dtype: str

In [57]:
# slicing
# print the alternate match runs 
kohli_series[::2]

0       1
2      13
4       1
6      34
8      21
       ..
206     0
208    58
210     0
212    73
214     7
Name: runs, Length: 108, dtype: int64

In [58]:
# fancy indexing
# find how much run virat made in 1,3,5,6 math
kohli_series[[1,3,5,6]]

1    23
3    12
5     9
6    34
Name: runs, dtype: int64

## Editing Series

In [59]:
# using indexing
# provide index number and the value
marks_series['history'] = 100
marks_series

math       100
english     90
science    100
history    100
Name: Mohit's marks, dtype: int64

In [60]:
# what if the index value doesn't exist
# it will create an index and add the value
# adding a subject named 'cs' 
marks_series['cs'] = 100 
marks_series

math       100
english     90
science    100
history    100
cs         100
Name: Mohit's marks, dtype: int64

In [61]:
# slicing 
runs[2:5] =100,100,99
runs

0      1
1     22
2    100
3    100
4     99
5     99
6     56
7     45
8     34
9     43
dtype: int64

In [62]:
# fancy indexing
runs

runs[[0,1,2,8]] = [0,0,0,1]
runs

0      0
1      0
2      0
3    100
4     99
5     99
6     56
7     45
8      1
9     43
dtype: int64

In [63]:
# using labeling
bolly_data.loc['2 States (2014 film)', 'lead'] = 'Kiara Advani'
bolly_data

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Kiara Advani
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

## Series with python functionality

In [64]:
# len
print(len(df))

365

In [65]:
# len of runs
print(len(kohli_runs))

215

In [66]:
# max
# maximum runs by virat kohli
print(kohli_series.max())

113

In [67]:
# dir it tells us about the attributes and method in series
print(dir(df))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_attrs', '_binop', '_can_hold_na', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_ixs', '_logical_func', '_logical_method', '_map_values', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'between', 'between_time', 'bfill', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [68]:
# sorted
print(sorted(df))

[33, 33, 35, 37, 39, 40, 40, 40, 40, 42, 42, 43, 44, 44, 44, 45, 46, 46, 48, 49, 49, 49, 49, 50, 50, 50, 51, 54, 56, 56, 56, 56, 57, 61, 62, 64, 65, 65, 66, 66, 66, 66, 67, 68, 70, 70, 70, 71, 71, 72, 72, 72, 72, 72, 73, 74, 74, 75, 76, 76, 76, 76, 77, 77, 78, 78, 78, 79, 79, 80, 80, 80, 81, 81, 82, 82, 83, 83, 83, 84, 84, 84, 85, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 92, 92, 92, 93, 93, 93, 93, 95, 95, 96, 96, 96, 96, 97, 97, 98, 98, 99, 99, 100, 100, 100, 101, 101, 101, 102, 102, 103, 103, 104, 104, 104, 105, 105, 105, 105, 105, 105, 105, 105, 105, 108, 108, 108, 108, 108, 108, 109, 109, 110, 110, 110, 111, 111, 112, 113, 113, 113, 114, 114, 114, 114, 115, 115, 115, 115, 117, 117, 117, 118, 118, 119, 119, 119, 119, 120, 122, 123, 123, 123, 123, 123, 124, 125, 126, 127, 128, 128, 129, 130, 131, 131, 132, 132, 134, 134, 134, 135, 135, 136, 136, 136, 137, 138, 138, 138, 139, 140, 144, 145, 146, 146, 146, 146, 147, 149, 150, 150, 150, 150, 151, 152, 152, 152, 153, 153, 153, 154, 154, 154, 155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 158, 158, 159, 159, 160, 160, 160, 160, 162, 164, 166, 167, 167, 168, 170, 170, 170, 170, 171, 172, 172, 173, 173, 173, 174, 174, 175, 175, 176, 176, 177, 178, 179, 179, 180, 180, 180, 182, 183, 183, 183, 184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 188, 189, 190, 190, 192, 192, 192, 196, 196, 196, 197, 197, 202, 202, 202, 203, 204, 206, 207, 209, 210, 210, 211, 212, 213, 214, 216, 219, 220, 221, 221, 222, 222, 224, 225, 225, 226, 227, 228, 229, 230, 231, 233, 236, 236, 237, 241, 243, 244, 245, 247, 249, 254, 254, 258, 259, 259, 261, 261, 265, 267, 268, 269, 276, 276, 290, 295, 301, 306, 312, 396]

#### type conversion

In [69]:
# converting this series into list using list()
list(marks_series)

[100, 90, 100, 100, 100]

In [70]:
# converting this series into dictionary using dict()
print(dict(marks_series))

{'math': np.int64(100), 'english': np.int64(90), 'science': np.int64(100), 'history': np.int64(100), 'cs': np.int64(100)}

#### membership operator

In [71]:
# check whether Zindagi Na Milegi Dobara this movie is present in this series ot not usng in 

# in operator work in index
'Uri: The Surgical Strike' in bolly_series.values

True

In [72]:
# looping

# loops work in values
for i in bolly_series:
    print(i)

Uri: The Surgical Strike
Battalion 609
The Accidental Prime Minister (film)
Why Cheat India
Evening Shadows
Soni (film)
Fraud Saiyaan
Bombairiya
Manikarnika: The Queen of Jhansi
Thackeray (film)
Amavas
Gully Boy
Hum Chaar
Total Dhamaal
Sonchiriya
Badla (2019 film)
Mard Ko Dard Nahi Hota
Hamid (film)
Photograph (film)
Risknamaa
Mere Pyare Prime Minister
22 Yards
Kesari (film)
Notebook (2019 film)
Junglee (2019 film)
Gone Kesh
Albert Pinto Ko Gussa Kyun Aata Hai?
The Tashkent Files
Kalank
Setters (film)
Student of the Year 2
PM Narendra Modi
De De Pyaar De
India's Most Wanted (film)
Yeh Hai India
Khamoshi (2019 film)
Kabir Singh
Article 15 (film)
One Day: Justice Delivered
Hume Tumse Pyaar Kitna
Super 30 (film)
Family of Thakurganj
Batla House
Jhootha Kahin Ka
Judgementall Hai Kya
Chicken Curry Law
Arjun Patiala
Jabariya Jodi
Pranaam
The Sky Is Pink
Mission Mangal
Saaho
Dream Girl (2019 film)
Section 375
The Zoya Factor (film)
Pal Pal Dil Ke Paas
Prassthanam
P Se Pyaar F Se Faraar
Ghost (2019 film)
Bala (2019 film)
Yaaram (2019 film)
Housefull 4
Saand Ki Aankh
Made in China (2019 film)
Ujda Chaman
Bypass Road (film)
Satellite Shankar
Jhalki
Marjaavaan
Motichoor Chaknachoor
Keep Safe Distance (film)
Pagalpanti (2019 film)
Ramprasad Ki Tehrvi
Yeh Saali Aashiqui
Dil Bechara
Pati Patni Aur Woh (2019 film)
Commando 3 (film)
Mardaani 2
Dabangg 3
Good Newwz
Kaalakaandi
Vodka Diaries
My Birthday Song
Nirdosh
Mukkabaaz
Union Leader (film)
Love per Square Foot
Aiyaary
Padmaavat
Kuchh Bheege Alfaaz
Jaane Kyun De Yaaron
Veerey Ki Wedding
Sonu Ke Titu Ki Sweety
Hate Story 4
Dil Juunglee
3 Storeys
Raid (2018 film)
Hichki
Missing (2018 film)
Baaghi 2
October (2018 film)
Mercury (film)
Beyond the Clouds (2017 film)
Nanu Ki Jaanu
Daas Dev
Omerta (film)
Raazi
Hope Aur Hum
High Jack (film)
Khajoor Pe Atke
Parmanu: The Story of Pokhran
Bioscopewala
Bhavesh Joshi Superhero
Phamous
Race 3
Dhadak
Sanju
Saheb Biwi Aur Gangster 3
Nawabzaade
Mulk (film)
Brij Mohan Amar Rahe
Karwaan
Gold (2018 film)
Satyameva Jayate (2018 film)
Happy Phirr Bhag Jayegi
Genius (2018 Hindi film)
Yamla Pagla Deewana: Phir Se
Stree (2018 film)
Paltan (film)
Laila Majnu (2018 film)
Gali Guleiyan
Halkaa
Pataakha
Batti Gul Meter Chalu
Love Sonia
Manto (2018 film)
Ishqeria
Manmarziyaan
Mitron
Sui Dhaaga
Baazaar
Jalebi (film)
FryDay
Tumbbad
Helicopter Eela
Namaste England
Andhadhun
Badhaai Ho
5 Weddings
Kaashi in Search of Ganga
Dassehra
The Journey of Karma
Jack and Dil
Mohalla Assi
Pihu
Bhaiaji Superhit
Rajma Chawal
Zero (2018 film)
Simmba
Tiger Zinda Hai
Golmaal Again
Judwaa 2
Ok Jaanu
Coffee with D
Kaabil
Raees (film)
Thugs of Hindostan
Hind Ka Napak Ko Jawab: MSG Lion Heart 2
Running Shaadi
The Ghazi Attack
Irada (2017 film)
Rangoon (2017 Hindi film)
Wedding Anniversary
Jeena Isi Ka Naam Hai (film)
Badrinath Ki Dulhania
Trapped (2016 Hindi film)
Aa Gaya Hero
Mantra (2016 film)
Phillauri (film)
Machine (2017 film)
Bhanwarey
Anaarkali of Aarah
Naam Shabana
Hotel Salvation
Begum Jaan
Noor (film)
Ek Thi Rani Aisi Bhi
Maatr
Sarkar 3
Jattu Engineer
Half Girlfriend (film)
Meri Pyaari Bindu
Sachin: A Billion Dreams
Hindi Medium
Sweetiee Weds NRI
Dobaara: See Your Evil
Flat 211
Dear Maya
Raabta (film)
Behen Hogi Teri
Tubelight (2017 Hindi film)
Bank Chor
Ek Haseena Thi Ek Deewana Tha
Jagga Jasoos
Shab (film)
Lipstick Under My Burkha
Bachche Kachche Sachche
G Kutta Se
Indu Sarkar
Jab Harry Met Sejal
Munna Michael
Toilet: Ek Prem Katha
Mubarakan
Guest iin London
Bareilly Ki Barfi
Babumoshai Bandookbaaz
Yadvi – The Dignified Princess
Qaidi Band
Shubh Mangal Saavdhan
Raag Desh (film)
Daddy (2017 film)
Simran (film)
Lucknow Central
A Gentleman
Viceroy's House (film)
Patel Ki Punjabi Shaadi
Newton (film)
The Final Exit
Bhoomi (film)
Haseena Parkar
JD (film)
Haraamkhor
Poster Boys
Mom (film)
Chef (2017 film)
Ranchi Diaries
Babuji Ek Ticket Bambai
Rukh (film)
Secret Superstar
Aval (2017 film)
Ribbon (film)
Shaadi Mein Zaroor Aana
Jia Aur Jia
Qarib Qarib Singlle
Aksar 2
Panchlait
Tumhari Sulu
Julie 2
Kadvi Hawa
Firangi
Fukrey Returns
Monsoon Shootout
Ajji
Chalk n Duster
Rebellious Flower
Saankal
Airlift (film)
Sallu Ki Shaadi
Irudhi Suttru
Kyaa Kool Hain Hum 3
Mastizaade
Dil Jo Na Keh Saka
Jugni (2016 film)
Ghayal: Once Again
Fitoor
Sanam Re
Direct Ishq
Ishq Forever
Loveshhuda
Neerja
Aligarh (film)
Bollywood Diaries
Love Shagun
Tere Bin Laden: Dead or Alive
Jai Gangaajal
Kapoor & Sons
Rocky Handsome
Love Games (film)
Fan (film)
Nil Battey Sannata
Laal Rang
Baaghi (2016 film)
Global Baba
Shortcut Safari
The Blueberry Hunt
Santa Banta Pvt Ltd
Traffic (2016 film)
1920: London
Azhar (film)
Buddha in a Traffic Jam
Murari the Mad Gentleman
Dear Dad (film)
Phobia (2016 film)
Sarbjit (film)
Veerappan (2016 film)
Do Lafzon Ki Kahani (film)
Te3n
Udta Punjab
Khel Toh Ab Shuru Hoga
Luv U Alia
7 Hours to Go
Raman Raghav 2.0
Junooniyat
Rough Book
Dhanak
Fredrick (film)
Dil Toh Deewana Hai
Sultan (2016 film)
Brahman Naman
Great Grand Masti
Waiting (2015 film)
Ishq Click
M Cream
Madaari
Dishoom
Fever (2016 film)
Rustom (film)
Hai Apna Dil Toh Awara
Mohenjo Daro (film)
Happy Bhag Jayegi
Waarrior Savitri
A Flying Jatt
Baar Baar Dekho
Freaky Ali
Raaz: Reboot
Pink (2016 film)
Parched
Banjo (2016 film)
Days of Tafree
Wah Taj
Island City (2015 film)
Ek Kahani Julie Ki
M.S. Dhoni: The Untold Story
MSG: The Warrior Lion Heart
Devi (2016 film)
Motu Patlu: King of Kings
Anna (2016 film)
Fuddu
Saat Uchakkey
Beiimaan Love
Umrika
Shivaay
Dongari Ka Raja
Ae Dil Hai Mushkil
Tum Bin II
Rock On 2
Force 2
Dear Zindagi
Befikre
Moh Maya Money
Shorgul
Saansein
Ki & Ka
Wajah Tum Ho
Dangal (film)
Mirzya (film)
Prem Ratan Dhan Payo
Tanu Weds Manu: Returns
Tanu Weds Manu: Returns
31st October (film)
ABCD 2
Dilwale (2015 film)
Bajrangi Bhaijaan
Bajirao Mastani
Welcome Back (film)
Baby (2015 Hindi film)
Singh Is Bliing
Gabbar Is Back
Gabbar Is Back
Mumbai Can Dance Saala
Alone (2015 Hindi film)
Tevar
Sharafat Gayi Tel Lene
Dolly Ki Doli
Hawaizaada
Khamoshiyan
Rahasya
Jai Jawaan Jai Kisaan (film)
Shamitabh
Roy (film)
Badlapur (film)
Crazy Cukkad Family
Take It Easy (2015 film)
Qissa (film)
Ab Tak Chhappan 2
Dum Laga Ke Haisha
Dirty Politics (film)
MSG: The Messenger
Badmashiyaan
Coffee Bloom
Hey Bro
NH10 (film)
Hunterrr
Detective Byomkesh Bakshy!
Luckhnowi Ishq
Court (film)
Margarita with a Straw
Ek Paheli Leela
Barkhaa
Mr. X (2015 film)
NH-8 Road to Nidhivan
Dilliwali Zaalim Girlfriend
Dharam Sankat Mein
Kaagaz Ke Fools
Kuch Kuch Locha Hai
Piku
Bombay Velvet
I Love Desi
Dil Dhadakne Do
Welcome 2 Karachi
P Se PM Tak
Mere Genie Uncle
Hamari Adhuri Kahani
Miss Tanakpur Haazir Ho
Uvaa
Ishq Ke Parindey
Ishqedarriyaan
Sabki Bajegi Band
Masaan
Guddu Rangeela
Bezubaan Ishq
Aisa Yeh Jahaan
Second Hand Husband
I Love NY (2015 film)
Main Hoon Part-Time Killer
Kaun Kitne Paani Mein
Drishyam (2015 film)
Bangistan
All Is Well (2015 film)
Brothers (2015 film)
Gour Hari Dastaan
Manjhi – The Mountain Man
Thoda Lutf Thoda Ishq
Phantom (2015 film)
Hero (2015 Hindi film)
Sorry Daddy
Talvar (film)
Katti Batti
Meeruthiya Gangsters
MSG-2 The Messenger
Calendar Girls (2015 film)
Bhaag Johnny
Jazbaa
Bumper Draw
Chinar Daastaan-E-Ishq
Kis Kisko Pyaar Karoon
Pyaar Ka Punchnama 2
Wedding Pullav
Shaandaar
Titli (2014 film)
Guddu Ki Gun
The Silent Heroes
Ranbanka
Sholay
Dedh Ishqiya
Karle Pyaar Karle
Om-Dar-B-Dar
Paranthe Wali Gali
Strings of Passion
Gunday
Jai Ho (film)
Hasee Toh Phasee
Heartless (2014 film)
Ya Rab
Darr @ the Mall
One by Two (2014 film)
Babloo Happy Hai
Highway (2014 Hindi film)
Gulabi Gang (film)
Shaadi Ke Side Effects
Gulaab Gang
Queen (2014 film)
Bewakoofiyaan
Total Siyapaa
Karar: The Deal
Lakshmi (2014 film)
Ragini MMS 2
Dishkiyaoon
Ankhon Dekhi
Gang of Ghosts
Anuradha (2014 film)
W (2014 film)
O Teri
Honour Killing (film)
2 States (2014 film)
Jal (film)
Bhoothnath Returns
Main Tera Hero
Lucky Kabootar
Station (2014 film)
Youngistaan
Samrat & Co.
Purani Jeans
Kya Dilli Kya Lahore
Koyelaanchal
Manjunath (film)
Dekh Tamasha Dekh
Mastram
The Xposé
Children of War (2014 film)
Hawaa Hawaai
Kahin Hai Mera Pyar
Kuku Mathur Ki Jhand Ho Gayi
Heropanti
CityLights (2014 film)
Filmistaan
Revolver Rani
Kaanchi: The Unbreakable
Machhli Jal Ki Rani Hai
Khwaabb
Yeh Hai Bakrapur
Ek Villain
Bobby Jasoos
Humshakals
Humpty Sharma Ki Dulhania
Hate Story 2
Lekar Hum Deewana Dil
Riyasat (film)
Amit Sahni Ki List
Holiday: A Soldier Is Never Off Duty
Fugly (film)
Bazaar E Husn
Pizza (2014 film)
Entertainment (2014 film)
Singham Returns
Mardaani
Raja Natwarlal
Mary Kom (film)
Creature 3D
Finding Fanny
Khoobsurat (2014 film)
3 A.M. (2014 film)
Kick (2014 film)
Mad About Dance
Mumbhai Connection
Life Is Beautiful (2014 film)
Desi Kattey
Haider (film)
Bang Bang!
Spark (2014 film)
Daawat-e-Ishq
Balwinder Singh Famous Ho Gaya
Jigariyaa
Tamanchey
Mumbai 125 KM
Meinu Ek Ladki Chaahiye
Chaarfutiya Chhokare
Sonali Cable
Happy New Year (2014 film)
Super Nani
Ekkees Toppon Ki Salaami
Rang Rasiya
The Shaukeens
Roar: Tigers of the Sundarbans
A Decent Arrangement
Gollu Aur Pappu
Titoo MBA
Kill Dil
Ungli
Happy Ending (film)
Zed Plus
Zid (2014 film)
Action Jackson (2014 film)
Bhopal: A Prayer for Rain
Mumbai Delhi Mumbai
Badlapur Boys
Main Aur Mr. Riight
Ugly (film)
PK (film)
Dehraadun Diary
Matru Ki Bijlee Ka Mandola
Sulemani Keeda
Inkaar (2013 film)
Gangoobai
Akaash Vani
Main Krishna Hoon
Race 2
Bandook
Listen... Amaya
Special 26
Murder 3
Zila Ghaziabad
Kai Po Che!
Bloody Isshq
Saare Jahaan Se Mehnga
3G (film)
Mere Dad Ki Maruti
Jolly LLB
Saheb Biwi Aur Gangster Returns
Mai (2013 film)
Vishwaroopam
Rangrezz
Aashiqui 2
Ek Thi Daayan
Himmatwala (2013 film)
Nautanki Saala!
Jayantabhai Ki Luv Story
Commando: A One Man Army
Bombay Talkies (film)
Go Goa Gone
Gippi
Aurangzeb (film)
Ishkq in Paris
Zindagi 50-50
Yeh Jawaani Hai Deewani
Fukrey
Chhota Bheem and the Throne of Bali
Raanjhanaa
Ankur Arora Murder Case
Shortcut Romeo
Ghanchakkar (film)
Hum Hai Raahi Car Ke
Policegiri
Bhaag Milkha Bhaag
Sixteen (2013 Indian film)
B.A. Pass
Enemmy
Issaq
Bajatey Raho
Luv U Soniyo
Nasha (film)
Chor Chor Super Chor
Calapor (film)
Love in Bombay
D-Day (2013 film)
Siddharth (2013 film)
Once Upon ay Time in Mumbai Dobaara!
Madras Cafe
Satyagraha (film)
Shuddh Desi Romance
Ramaiya Vastavaiya
Chennai Express
Grand Masti
John Day (film)
Horror Story (film)
Phata Poster Nikhla Hero
Ship of Theseus (film)
The Lunchbox
Baat Bann Gayi
Boss (2013 Hindi film)
Shahid (film)
Mickey Virus
Satya 2
Rajjo
Maazii
Sooper Se Ooper
Prague (2013 film)
Wake Up India
Super Model (film)
Gori Tere Pyaar Mein
What the Fish
Jackpot (2013 film)
Table No. 21
Bullett Raja
Dhoom 3
Chashme Baddoor (2013 film)
Lootera
War Chhod Na Yaar
Chaalis Chauraasi
Ghost (2012 film)
Sadda Adda
Singh Saab the Great
Goliyon Ki Raasleela Ram-Leela
Agneepath (2012 film)
Ek Main Aur Ekk Tu
Ekk Deewana Tha
?: A Question Mark
Jodi Breakers
Tere Naal Love Ho Gaya
Staying Alive (2012 film)
Paan Singh Tomar (film)
Kahaani
Zindagi Tere Naam
Agent Vinod (2012 film)
Blood Money (2012 film)
Bumboo
Valentine's Night
Married 2 America
Chaar Din Ki Chandni
Bittoo Boss
Vicky Donor
Hate Story
Tezz
Dangerous Ishhq
Ishaqzaade
Department (film)
Fatso!
Arjun: The Warrior Prince
Life Ki Toh Lag Gayi
Shanghai (2012 film)
Ferrari Ki Sawaari
Teri Meri Kahaani (film)
Mr. Bhatti on Chutti
Yeh Khula Aasmaan
Rakhtbeej
Gangs of Wasseypur
Gangs of Wasseypur – Part 2
Cocktail (2012 film)
Gattu
Kyaa Super Kool Hain Hum
Maximum (film)
Paanch Ghantey Mien Paanch Crore
Ek Tha Tiger
Challo Driver
Shirin Farhad Ki Toh Nikal Padi
Joker (2012 film)
Aalaap (film)
Mere Dost Picture Abhi Baki Hai
Krishna Aur Kans
From Sydney with Love
Jalpari: The Desert Mermaid
Barfi!
Heroine (2012 film)
Chal Pichchur Banate Hain
Kismat Love Paisa Dilli
Jeena Hai Toh Thok Daal
OMG – Oh My God!
Aiyyaa
Chittagong (film)
Bhoot Returns
Delhi Safari
Chakravyuh (2012 film)
Student of the Year
Ajab Gazabb Love
Rush (2012 film)
1920: The Evil Returns
Sons of Ram
Ata Pata Laapata
Jab Tak Hai Jaan
Talaash: The Answer Lies Within
Login (film)
Son of Sardaar
Cigarette Ki Tarah
Dabangg 2
Players (2012 film)
Housefull 2
Bol Bachchan
English Vinglish
Impatient Vivek
Yamla Pagla Deewana
Mumbai Mast Kallander
Dhobi Ghat (film)
Turning 30
Hostel (2011 film)
Dil Toh Baccha Hai Ji
United Six
Utt Pataang
Patiala House (film)
7 Khoon Maaf
Tanu Weds Manu
F.A.L.T.U
Memories in March
Thank You (2011 film)
Angel (2011 film)
Happy Husbands (2011 film)
Teen Thay Bhai
Dum Maaro Dum (film)
Shor in the City
Zokkomon
Chalo Dilli
Aashiqui.in
Satrangee Parachute
Monica (film)
I Am (2010 Indian film)
Naughty @ 40
Haunted – 3D
Love U...Mr. Kalakaar!
Ragini MMS
Stanley Ka Dabba
Shagird (2011 film)
404 (film)
Shaitan (film)
Pyaar Ka Punchnama
Bheja Fry 2
Always Kabhi Kabhi
Double Dhamaal
Bbuddah... Hoga Terra Baap
Delhi Belly (film)
Murder 2
Chillar Party
Zindagi Na Milegi Dobara
Dear Friend Hitler
I Am Kalam
Bin Bulaye Baraati
Kucch Luv Jaisaa
Singham
Khap (film)
Bubble Gum (film)
Shabri
Phhir
Aarakshan
Chatur Singh Two Star
Sahi Dhandhe Galat Bande
Bodyguard (2011 Hindi film)
Yeh Dooriyan
Not a Love Story (2011 film)
Hum Tum Shabana
Mummy Punjabi
Mere Brother Ki Dulhan
Mausam (2011 film)
U R My Jaan
Force (2011 film)
Saheb Biwi Aur Gangster
Tere Mere Phere
Breakaway (2011 film)
Chargesheet (film)
Love Breakups Zindagi
Mujhse Fraaandship Karoge
Aazaan
Ra.One
Rockstar (2011 film)
Miley Naa Miley Hum
Tell Me O Kkhuda
Damadamm!
Ladies vs Ricky Bahl
Desi Boyz
Game (2011 film)
No One Killed Jessica
Rascals (2011 film)
The Dirty Picture
Pyaar Impossible!
Chance Pe Dance
My Friend Pinto
Veer (2010 film)
Striker (2010 film)
Rann (film)
Ishqiya
Road to Sangam
Jo Hum Chahein
Click (2010 film)
Toh Baat Pakki!
My Name Is Khan
Teen Patti (film)
Karthik Calling Karthik
Don 2
Rokkk
Aakhari Decision
Right Yaaa Wrong
Sukhmani: Hope for Life
Thanks Maa
Na Ghar Ke Na Ghaat Ke
Trump Card (film)
Shaapit
Hum Tum Aur Ghost
Well Done Abba
Tum Milo Toh Sahi
Jaane Kahan Se Aayi Hai
Prem Kaa Game
Sadiyaan
The Japanese Wife
Paathshaala
Phoonk 2
Lahore (film)
Apartment (film)
City of Gold (2010 film)
Chase (2010 film)
Housefull (2010 film)
Mittal v/s Mittal
It's a Wonderful Afterlife
Prince (2010 film)
Raavan
Bumm Bumm Bole
Kushti (film)
Kites (film)
Love Sex Aur Dhokha
Milenge Milenge
Ek Second... Jo Zindagi Badal De?
Mr. Singh Mrs. Mehta
Lamhaa
Khatta Meetha (2010 film)
Tere Bin Laden
Udaan (2010 film)
Once Upon a Time in Mumbaai
Help (film)
Peepli Live
Lafangey Parindey
Hello Darling
Antardwand
Aashayein
Soch Lo
Dabangg
Khichdi: The Movie
Red Alert: The War Within
Life Express (2010 film)
The Film Emotional Atyachar
Hisss
Crook (film)
Do Dooni Chaar
Aakrosh (2010 film)
Ramayana: The Epic
Knock Out (2010 film)
Jhootha Hi Sahi
Guzaarish (film)
Allah Ke Banday
Break Ke Baad
Khuda Kasam
Phas Gaye Re Obama
Malik Ek
A Flat (film)
No Problem (2010 film)
Band Baaja Baaraat
Kaalo
Mirch
Tees Maar Khan (2010 film)
Isi Life Mein
Toonpur Ka Super Hero
Tera Kya Hoga Johnny
Ramaa: The Saviour
I Hate Luv Storys
Dulha Mil Gaya
Anjaana Anjaani
Dunno Y... Na Jaane Kyon
Pankh
Action Replayy
3 Idiots
Luck by Chance
Love Aaj Kal
Wanted (2009 film)
Delhi-6
Raaz: The Mystery Continues
Aasma: The Sky Is the Limit
Ajab Prem Ki Ghazab Kahani
Chal Chala Chal
Billu
The Stoneman Murders
Kisse Pyaar Karoon
Dhoondte Reh Jaaoge
Karma Aur Holi
Victory (2009 film)
Kaminey
Jai Veeru
Little Zizou
Gulaal (film)
Aloo Chaat (film)
Barah Aana
Firaaq
Aa Dekhen Zara
99 (2009 film)
Ek: The Power of One
Ek Se Bure Do
Sikandar (2009 film)
Zor Lagaa Ke...Haiya!
Paying Guests
New York (2009 film)
Sankat City
Shortkut
Luck (2009 film)
Life Partner
Daddy Cool (2009 Hindi film)
Kisaan
Yeh Mera India
Aagey Se Right
Chintu Ji
Quick Gun Murugun
Fox (film)
Baabarr
Phir Kabhi
Vaada Raha
Dil Bole Hadippa!
What's Your Raashee?
Acid Factory
All the Best: Fun Begins
Wake Up Sid
Main Aurr Mrs Khanna
Blue (2009 film)
Fruit and Nut (film)
Aladin (film)
London Dreams
Jail (2009 film)
Tum Mile
Kurbaan (2009 film)
De Dana Dan
Paa (film)
Rocket Singh: Salesman of the Year
Raat Gayi Baat Gayi?
Accident on Hill Road
Chandni Chowk to China
Dostana (2008 film)
Race (2008 film)
Rab Ne Bana Di Jodi
Ghajini (2008 film)
Singh Is Kinng
Golmaal Returns
Jodhaa Akbar
Bachna Ae Haseeno
Bhoothnath
Sarkar Raj
Halla Bol
Humne Jeena Seekh Liya
Bombay to Bangkok
Tulsi (film)
Sunday (2008 film)
One Two Three
Krazzy 4
U Me Aur Hum
Sirf (film)
Tashan (film)
Anamika (2008 film)
Jimmy (2008 film)
Jannat (film)
Don Muthu Swami
Woodstock Villa
Mere Baap Pehle Aap
Summer 2007
De Taali
Haal-e-Dil
Thodi Life Thoda Magic
Thoda Pyaar Thoda Magic
Via Darjeeling
Kismat Konnection
Love Story 2050
Contract (2008 film)
Mission Istaanbul
Money Hai Toh Honey Hai
God Tussi Great Ho
Mumbai Meri Jaan
Maan Gaye Mughal-e-Azam
Rock On!!
C Kkompany
Chamku
Mukhbiir
Tahaan
1920 (film)
The Last Lear
Welcome to Sajjanpur
Saas Bahu Aur Sensex
Hari Puttar: A Comedy of Terrors
Drona (2008 film)
Hello (2008 film)
Karzzzz
Heroes (2008 film)
Roadside Romeo
Ek Vivaah... Aisa Bhi
Deshdrohi
Fashion (2008 film)
Dasvidaniya
Yuvvraaj
Oye Lucky! Lucky Oye!
Oh My God (2008 film)
Sorry Bhai!
1971 (2007 film)
Meerabai Not Out
Wafa: A Deadly Love Story
Gumnaam – The Mystery
Dil Kabaddi
Aag (2007 film)
Aap Kaa Surroor
Aggar (film)
Anwar (2007 film)
Aaja Nachle
Apne
Awarapan
Bheja Fry (film)
Bhool Bhulaiyaa
Bhram
Big Brother (2007 film)
68 Pages
Aur Pappu Paas Ho Gaya
Apna Asmaan
Black Friday (2007 film)
The Blue Umbrella (2005 film)
Blood Brothers (2007 Indian film)
Buddha Mar Gaya
Cash (2007 film)
Cheeni Kum
Chhodon Naa Yaar
Darling (2007 Indian film)
Chak De! India
Dhamaal
Goal (2007 Hindi film)
Dharm (film)
Bombay to Goa (2007 film)
Dhokha
Dil Dosti Etc
Dhol (film)
Ek Chalis Ki Last Local
Familywala
Gandhi My Father
Don't Stop Dreaming
Dus Kahaniyaan
Eklavya: The Royal Guard
Go (2007 film)
Gauri: The Unborn
Heyy Babyy
Guru (2007 film)
Honeymoon Travels Pvt. Ltd.
Jahan Jaaeyega Hamen Paaeyega
Jhoom Barabar Jhoom
Jab We Met
Good Boy Bad Boy
Fool & Final
Khoya Khoya Chand
Johnny Gaddaar
Just Married (2007 film)
Kya Love Story Hai
Kudiyon Ka Hai Zamana
Hastey Hastey
Laaga Chunari Mein Daag
Life in a... Metro
Loins of Punjab Presents
Manorama Six Feet Under
Marigold (2007 film)
MP3: Mera Pehla Pehla Pyaar
Hattrick (film)
Naqaab
Mumbai Salsa
The Namesake (film)
Namastey London
My Bollywood Bride
Nehlle Pe Dehlla
Nishabd
No Smoking (2007 film)
Om Shanti Om
Partner (2007 film)
Raqeeb
Nanhe Jaisalmer
Life Mein Kabhie Kabhiee
Risk (2007 film)
Shakalaka Boom Boom
Red Swastik
Salaam-e-Ishq: A Tribute to Love
Saawariya
Sarhad Paar
Say Salaam India
Red: The Dark Side
Shootout at Lokhandwala
Strangers (2007 Hindi film)
Swami (2007 film)
Taare Zameen Par
Ta Ra Rum Pum
Speed (2007 film)
Traffic Signal (film)
The Train (2007 film)
Showbiz (film)
Sunglass (film)
Welcome (2007 film)
36 China Town
Zamaanat
Aap Ki Khatir (2006 film)
Ahista Ahista (2006 film)
Aksar
Alag
Anthony Kaun Hai?
Apna Sapna Money Money
Ankahee (2006 film)
Yatra (2007 film)
Baabul (2006 film)
Aisa Kyon Hota Hai?
Adharm (2006 film)
Being Cyrus
Banaras (2006 film)
Bas Ek Pal
Bhagam Bhag
Chingaari
Bhoot Unkle
Chand Ke Paar Chalo (film)
Aryan: Unbreakable
Chup Chup Ke
Corporate (2006 film)
Darna Zaroori Hai
Deadline: Sirf 24 Ghante
Dil Diya Hai
Darwaaza Bandh Rakho
Eight: The Power of Shani
Dhoom 2
Dor (film)
Don (2006 Hindi film)
Family (2006 film)
Fanaa (2006 film)
Gangster (2006 film)
Golmaal: Fun Unlimited
Devaki (2005 film)
Fight Club – Members Only
Dharti Kahe Pukar Ke (2006 film)
Humko Deewana Kar Gaye
Humko Tumse Pyaar Hai
I See You (2006 film)
Jaane Hoga Kya
Jaan-E-Mann
Jawani Diwani: A Youthful Joyride
Holiday (2006 film)
Iqraar by Chance
Khosla Ka Ghosla
Kabhi Alvida Naa Kehna
Love Ke Chakkar Mein
Lage Raho Munna Bhai
Kabul Express
Jigyaasa
Krrish
Malamaal Weekly
Omkara (2006 film)
Pyaar Ke Side Effects
Naksha
Phir Hera Pheri
Pyare Mohan
Mere Jeevan Saathi (2006 film)
Prateeksha
Sacred Evil – A True Story
Rang De Basanti
Shaadi Karke Phas Gaya Yaar
Sandwich (2006 film)
Shaadi Se Pehle
Saawan... The Love Season

In [73]:
# Arithmetic Operator
# find how much needed to get 100
100 - marks_series

math        0
english    10
science     0
history     0
cs          0
Name: Mohit's marks, dtype: int64

In [74]:
# Relational Operator

# find in how many matched virat kohli scores more than 50
50 >= kohli_series

0       True
1       True
2       True
3       True
4       True
       ...
210     True
211     True
212    False
213     True
214     True
Name: runs, Length: 215, dtype: bool

## Bollean Indexing on series

In [75]:
# find no. of 50's scored by virat kohli
kohli_series[kohli_series >= 50]

14      50
33      58
40      71
43      56
44      67
51      70
56      57
67      73
70      51
72      58
73      65
79      57
80      93
81      99
84      56
96      67
98      73
102     51
103     62
109     82
115     75
116     79
118     80
119    100
121     52
122    108
125    109
126     75
127    113
128     54
130     54
131     62
133     64
136     55
140     58
143     57
144     92
147     68
151     70
159     84
161     67
163    100
174     72
177     90
181     50
187     72
196     51
197     53
208     58
212     73
Name: runs, dtype: int64

In [76]:
# find total no. of matches in which virat kohli made more than 50
kohli_series[kohli_series >= 50].size

50

In [77]:
# find no. of duks
kohli_series[kohli_series == 0]

7      0
86     0
90     0
92     0
129    0
134    0
205    0
206    0
210    0
Name: runs, dtype: int64

In [78]:
# total no. of matches
kohli_series[kohli_series == 0].size

9

In [79]:
# find actor who have done more than 20 movies
num_movies = bolly_lead_series.value_counts()
num_movies[num_movies >20]

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64

## Excercise

In [80]:
# importing ipl data set
deliveries  = pd.read_csv('data/deliveries.csv')
deliveries.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [81]:
# Find top 10 batsman in terms of runs
deliveries.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [82]:
# find the batsman with max numbers of six
six = deliveries[deliveries['batsman_runs'] == 6]
six.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1)

batsman
CH Gayle    327
Name: batsman, dtype: int64

In [83]:
# find top 10 batsman with max number of 4's and 6's in the last 5 overs

# filter last 5 overs
last_overs = deliveries[deliveries['over'] > 15]

# keep only 4s and 6s
last_overs = last_overs[(last_overs['batsman_runs'] == 4) | (last_overs['batsman_runs'] == 6)]

# count per batsman
result = last_overs.groupby('batsman')['batsman'].count().sort_values(ascending=False)

print(result.head(10))

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
KA Pollard        206
V Kohli           160
YK Pathan         149
KD Karthik        145
Yuvraj Singh      130
AD Russell        129
AT Rayudu         114
Name: batsman, dtype: int64

In [84]:
# find virat kohli's record against all teams

# filtering only where the batsman is virat kohli
temp_df = deliveries[deliveries['batsman'] == 'V Kohli']

temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [85]:
# create a function that can return the highest score of any batsman

def highest(batsman):
    vk_df = deliveries[deliveries['batsman'] == batsman]
    return vk_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(2).values[0]

highest('R Sharma')

np.int64(14)