## Pandas

### Pandas Series -> it is like a column in a table. It is a 1D array holding data of any type

In [1]:
# importing pandas

import pandas as pd
import numpy as np

#### Series from lists

In [2]:
# string 

country =['India','Russia','USA','Japan']

# makeing series using .series() in pandas
# series has twwo things 1. index, 2. value
pd.Series(country)

0     India
1    Russia
2       USA
3     Japan
dtype: str

In [258]:
# integers

runs = [1,22,30,100,89,99,56,45,34,43]

# creating series
runs = pd.Series(runs)
runs

0      1
1     22
2     30
3    100
4     89
5     99
6     56
7     45
8     34
9     43
dtype: int64

#### custom indexing in series

In [228]:
marks = [90,23,57,34,23]
subject = ['Math','Hindi','English','Science','CS']

# creating series
# now make marks as value and subjects as index
# using index=(jise index banna cahte ho uska name)
marks = pd.Series(marks,index=subject)
marks

Math       90
Hindi      23
English    57
Science    34
CS         23
dtype: int64

#### Setting a name for series objects

In [5]:
# giving a name to this series
# using name parameter
pd.Series(marks,index=subject,name="Rohit's marks")

Math       90
Hindi      23
English    57
Science    34
CS         23
Name: Rohit's marks, dtype: int64

### Series from dictionary

In [6]:
# creating series from dictionary

# dictionary
sub_marks = {
    'math' : 100,
    'english' : 90,
    'science' : 100,
    'history' : 84,
}

In [239]:
# creating series from dictionary
marks_series = pd.Series(sub_marks,name="Mohit's marks")
marks_series

math       100
english     90
science    100
history     84
Name: Mohit's marks, dtype: int64

#### Series Attribute

In [8]:
# size attribute
# this tells us how many items are there in our series

# this will tell us about the size of our series
marks_series.size

4

In [9]:
# dtype
# this will tell us the type of data stored in series

marks_series.dtype

dtype('int64')

In [10]:
# name
# this will tell the name of our siries

marks_series.name

"Mohit's marks"

In [11]:
# is_unique
# this tells that all the items in a series are unique or not 
marks_series.is_unique

False

In [12]:
# index
# this will display all the index value in series

marks_series.index

Index(['math', 'english', 'science', 'history'], dtype='str')

In [13]:
# values
# this gives index object
# this will display all the value present in series

marks_series.values

array([100,  90, 100,  84])

## Series using read_csv

In [77]:
# importing subs.csv
df = pd.read_csv('data/subs.csv')


# creating series
df = df['Subscribers gained']
type(df)

pandas.Series

In [42]:
# reading data from csv file 

# reading kohli_ipl.csv data
kohli_runs = pd.read_csv('data/kohli_ipl.csv')
kohli_runs

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [45]:
# converting kohli_ipl.csv into series 
kohli_series = kohli_runs['runs']
kohli_series

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

In [59]:
# working with bollywood.csv

# reading bollywood.csv
bolly_data = pd.read_csv('data/bollywood.csv')
bolly_data

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [60]:
# making series of movie column
bolly_series = bolly_data['movie']
bolly_series

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1495                  Hum Tumhare Hain Sanam
1496                     Aankhen (2002 film)
1497                         Saathiya (film)
1498                          Company (film)
1499                    Awara Paagal Deewana
Name: movie, Length: 1500, dtype: str

In [61]:
# making series of lead column
bolly_lead_series = bolly_data['lead']
bolly_lead_series

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1495      Shah Rukh Khan
1496    Amitabh Bachchan
1497        Vivek Oberoi
1498          Ajay Devgn
1499        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [63]:
# making lead column -> index 
bolly_data = pd.read_csv('data/bollywood.csv',index_col='lead')
bolly_data

                                                 movie
lead
Vicky Kaushal                 Uri: The Surgical Strike
Vicky Ahuja                              Battalion 609
Anupam Kher       The Accidental Prime Minister (film)
Emraan Hashmi                          Why Cheat India
Mona Ambegaonkar                       Evening Shadows
...                                                ...
Shah Rukh Khan                  Hum Tumhare Hain Sanam
Amitabh Bachchan                   Aankhen (2002 film)
Vivek Oberoi                           Saathiya (film)
Ajay Devgn                              Company (film)
Akshay Kumar                      Awara Paagal Deewana

[1500 rows x 1 columns]

In [64]:
# making movie column -> index 
bolly_data = pd.read_csv('data/bollywood.csv',index_col='movie')
bolly_data

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

## Series Method

#### working with subs.csv data set

In [84]:
# head ->  Returns the first 5 rows of a Series (used for preview of data)
df.head

<bound method NDFrame.head of 0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64>

In [93]:
# tail ->  Returns the last 5 rows of a Series (used for preview of data)
df.tail

# if you want to see specific number of tails use
# df.tail(10) -> this will print last 10 rows of the data

<bound method NDFrame.tail of 0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64>

In [95]:
# sample -> picks up one random row from the data 
df.sample

<bound method NDFrame.sample of 0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64>

#### working with kohli.csv

In [88]:
# head ->  Returns the first 5 rows of a Series (used for preview of data)
kohli_runs.head(10)

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1
5         6     9
6         7    34
7         8     0
8         9    21
9        10     3

In [107]:
# tail ->  Returns the last 5 rows of a Series (used for preview of data)
kohli_runs.tail(10)

# if you want to see specific number of tails use
# kohli_runs.tail(10) -> this will print last 10 rows of the data

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [119]:
# sample
kohli_runs.sample

<bound method NDFrame.sample of      match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]>

In [127]:
# find the highest score of virat kohli

# dataframe
# kohli_runs.sort_values(by='runs',ascending=False)

# series
# sort_values do temporary changes in the series
# this is also the example of method chaining
kohli_series.sort_values(ascending=False)

# if we want to change our original series -> use inplace=True and this will permanently change the series

127    113
125    109
122    108
163    100
119    100
      ...
92       0
210      0
129      0
7        0
134      0
Name: runs, Length: 215, dtype: int64

### Working with bollywood.csv

In [109]:
# head
bolly_data.head(10)

                                                      lead
movie
Uri: The Surgical Strike                     Vicky Kaushal
Battalion 609                                  Vicky Ahuja
The Accidental Prime Minister (film)           Anupam Kher
Why Cheat India                              Emraan Hashmi
Evening Shadows                           Mona Ambegaonkar
Soni (film)                           Geetika Vidya Ohlyan
Fraud Saiyaan                                 Arshad Warsi
Bombairiya                                    Radhika Apte
Manikarnika: The Queen of Jhansi            Kangana Ranaut
Thackeray (film)                       Nawazuddin Siddiqui

In [105]:
# tail
bolly_data.tail(10)

                                        lead
movie
Raaz (2002 film)                  Dino Morea
Zameen (2003 film)                Ajay Devgn
Waisa Bhi Hota Hai Part II      Arshad Warsi
Devdas (2002 Hindi film)      Shah Rukh Khan
Kaante                      Amitabh Bachchan
Hum Tumhare Hain Sanam        Shah Rukh Khan
Aankhen (2002 film)         Amitabh Bachchan
Saathiya (film)                 Vivek Oberoi
Company (film)                    Ajay Devgn
Awara Paagal Deewana            Akshay Kumar

In [113]:
# sample 
bolly_data.sample()

                               lead
movie
Mohenjo Daro (film)  Hrithik Roshan

In [117]:
# value_counts -> tells us about the frequency of data 
bolly_data.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [136]:
# sort_index() -> sort all the index in a series
bolly_data.sort_index(ascending=True)

# permanently sorting the index (movie) column using inplace=True
bolly_data.sort_index(inplace=True)
bolly_data

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

## Series Math Methods

In [140]:
# count -> this counts all the total number of items present in a series and it dosen't counts the missing values
kohli_series.count()

np.int64(215)

In [142]:
# sum

# this will do the sum of all the runs made by virat kohli
kohli_runs['runs'].sum()

np.int64(6634)

In [149]:
# product
df.product()

np.int64(0)

### Statistical methods

In [154]:
# mean
df.mean()

np.float64(135.64383561643837)

In [153]:
# median
df.median()

np.float64(123.0)

In [157]:
# find mean of all the runs made by virat kohli
# or we can say this is the average run made by virat kohli
kohli_runs['runs'].mean()

np.float64(30.855813953488372)

In [159]:
# mode
df.mode()

0    105
Name: Subscribers gained, dtype: int64

In [167]:
# mode (frequently occuring score by virat)
kohli_series.mode()

0    0
Name: runs, dtype: int64

In [ ]:
# find which actor made most of the movies
# bolly_lead_series() -> actors (lead) column
bolly_lead_series .mode()

0    Akshay Kumar
Name: lead, dtype: str

In [166]:
# std -> it tells how spread out data is
df.std()

np.float64(62.6750230372527)

In [172]:
# var ->
kohli_series.var()

np.float64(688.0024777222343)

In [174]:
# min

# find maximum runs made by virat kohli
kohli_series.max()

np.int64(113)

In [175]:
# min

# find minimum runs made by virat kohli
kohli_series.min()

np.int64(0)

In [178]:
# find minimum number of movies made by actor/actoress
bolly_lead_series.min()

'Aadar Jain'

In [180]:
# describe -> it provies summary of the data

kohli_runs.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [182]:
# describe for bollywood
bolly_data.describe()

                lead
count           1500
unique           566
top     Akshay Kumar
freq              48

In [183]:
# describe for subs
df.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

## Series Indexing

In [186]:
# integer indexing

# creating a series
x =pd.Series([1,2,54,472,45,7,345,235,234])

In [190]:
# indexing 
# positive indexing
# syntax -> series_name[index number]
x[3]

np.int64(472)

In [198]:
# slicing
bolly_series[0]

'Uri: The Surgical Strike'

In [202]:
# slicing
# print the runs made by virat kohli between 5-15 matches
kohli_series[4:15]

4      1
5      9
6     34
7      0
8     21
9      3
10    10
11    38
12     3
13    11
14    50
Name: runs, dtype: int64

In [204]:
# negative slicing 
kohli_series[-5:]

210     0
211    20
212    73
213    25
214     7
Name: runs, dtype: int64

In [206]:
# negative slicing in movies
# las 5 movies
bolly_series[-5:]

1495    Hum Tumhare Hain Sanam
1496       Aankhen (2002 film)
1497           Saathiya (film)
1498            Company (film)
1499      Awara Paagal Deewana
Name: movie, dtype: str

In [208]:
# slicing
# print the alternate match runs 
kohli_series[::2]

0       1
2      13
4       1
6      34
8      21
       ..
206     0
208    58
210     0
212    73
214     7
Name: runs, Length: 108, dtype: int64

In [210]:
# fancy indexing
# find how much run virat made in 1,3,5,6 math
kohli_series[[1,3,5,6]]

1    23
3    12
5     9
6    34
Name: runs, dtype: int64

## Editing Series

In [240]:
# using indexing
# provide index number and the value
marks_series['history'] = 100
marks_series

math       100
english     90
science    100
history    100
Name: Mohit's marks, dtype: int64

In [241]:
# what if the index value doesn't exist
# it will create an index and add the value
# adding a subject named 'cs' 
marks_series['cs'] = 100 
marks_series

math       100
english     90
science    100
history    100
cs         100
Name: Mohit's marks, dtype: int64

In [250]:
# slicing 
runs[2:5] =100,100,99
runs

[1, 22, 100, 100, 99, 34, 43]

In [263]:
# fancy indexing
runs

runs[[0,1,2,8]] = [0,0,0,1]
runs

0      0
1      0
2      0
3    100
4     89
5     99
6     56
7     45
8      1
9     43
dtype: int64

In [268]:
# using labeling
bolly_data.loc['2 States (2014 film)', 'lead'] = 'Kiara Advani'
bolly_data

                                        lead 2 States (2014 film)
movie
1920 (film)                 Rajniesh Duggall         Kiara Advani
1920: London                   Sharman Joshi         Kiara Advani
1920: The Evil Returns           Vicky Ahuja         Kiara Advani
1971 (2007 film)              Manoj Bajpayee         Kiara Advani
2 States (2014 film)            Kiara Advani         Kiara Advani
...                                      ...                  ...
Zindagi 50-50                    Veena Malik         Kiara Advani
Zindagi Na Milegi Dobara      Hrithik Roshan         Kiara Advani
Zindagi Tere Naam         Mithun Chakraborty         Kiara Advani
Zokkomon                     Darsheel Safary         Kiara Advani
Zor Lagaa Ke...Haiya!          Meghan Jadhav         Kiara Advani

[1500 rows x 2 columns]