# Multi index series and Data Frame

In [1]:
import numpy as np
import pandas as pd

### Multi indexing and Hierarchical both are same

## Multi index Series

In [2]:
# multi index series

# using pd.MultiIndex.from_tuples()
index_val = [('cse',2023),('cse',2024),('cse',2025),('cse',2026),('cse_ai',2023),('cse_ai',2024),('cse_ai',2025),('cse_ai',2026)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([(   'cse', 2023),
            (   'cse', 2024),
            (   'cse', 2025),
            (   'cse', 2026),
            ('cse_ai', 2023),
            ('cse_ai', 2024),
            ('cse_ai', 2025),
            ('cse_ai', 2026)],
           )

In [3]:
# multi index series

# using pd.MultiIndex.from_tuples()
pd.MultiIndex.from_product([['cse','cse_ai'],[2021,2022,2023,2024,2025,2026]])

MultiIndex([(   'cse', 2021),
            (   'cse', 2022),
            (   'cse', 2023),
            (   'cse', 2024),
            (   'cse', 2025),
            (   'cse', 2026),
            ('cse_ai', 2021),
            ('cse_ai', 2022),
            ('cse_ai', 2023),
            ('cse_ai', 2024),
            ('cse_ai', 2025),
            ('cse_ai', 2026)],
           )

In [4]:
 # creating series from multi index object
s = pd.Series([1,2,3,4,5,6,7,8],index=multiindex)
s

cse     2023    1
        2024    2
        2025    3
        2026    4
cse_ai  2023    5
        2024    6
        2025    7
        2026    8
dtype: int64

In [5]:
# fetch 4
print(s[('cse',2026)])

4

In [6]:
# fetch all cse_ai 
s['cse_ai']

2023    5
2024    6
2025    7
2026    8
dtype: int64

In [7]:
# unstack -> using unstack we can convert multi index series into a data frame
temp = s.unstack()
temp

        2023  2024  2025  2026
cse        1     2     3     4
cse_ai     5     6     7     8

In [8]:
# stack -> using stack we can convert a data frame into a series
# temp is a data frame
temp.stack()

cse     2023    1
        2024    2
        2025    3
        2026    4
cse_ai  2023    5
        2024    6
        2025    7
        2026    8
dtype: int64

## Multi index Series

In [12]:
branch_df1 = pd.DataFrame([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12],
    [13,14],
    [15,16]
], index=multiindex,columns=['average_package','students'])
branch_df1

             average_package  students
cse    2023                1         2
       2024                3         4
       2025                5         6
       2026                7         8
cse_ai 2023                9        10
       2024               11        12
       2025               13        14
       2026               15        16

In [13]:
# fetch all the cse_ai data 
branch_df1.loc['cse_ai']

      average_package  students
2023                9        10
2024               11        12
2025               13        14
2026               15        16

In [22]:
# multi index data frame from column perspective
branch_df2 = pd.DataFrame([
    [1,2,4,0],
    [3,4,0,9],
    [5,6,4,0],
    [7,8,0,3],
],index=[2023,2024,2025,2026],columns= pd.MultiIndex.from_product([['delhi','mumbai'],['average_package','students']])) # we did column based multi indexing

branch_df2

               delhi                   mumbai
     average_package students average_package students
2023               1        2               4        0
2024               3        4               0        9
2025               5        6               4        0
2026               7        8               0        3

In [24]:
# fetch mumbai's students average package
branch_df2['mumbai']['average_package']

2023    4
2024    0
2025    4
2026    0
Name: average_package, dtype: int64

In [25]:
# fetching row
# fetch 2026 row
branch_df2.loc[2026]

delhi   average_package    7
        students           8
mumbai  average_package    0
        students           3
Name: 2026, dtype: int64

In [27]:
# multi index data frame in terms of both rows and columns
branch_df3 = pd.DataFrame([
    [1,2,2,8],
    [3,4,5,0],
    [5,6,3,0],
    [7,8,0,8],
    [9,10,10,38],
    [11,12,28,9],
    [13,14,90],
    [15,16,14]
],
index=multiindex,columns=pd.MultiIndex.from_product([['delhi','mumbai'],['average_package','students']])
)
branch_df3 # this is a 4D data represented using 2d structure that is  data frame

                      delhi                   mumbai
            average_package students average_package students
cse    2023               1        2               2      8.0
       2024               3        4               5      0.0
       2025               5        6               3      0.0
       2026               7        8               0      8.0
cse_ai 2023               9       10              10     38.0
       2024              11       12              28      9.0
       2025              13       14              90      NaN
       2026              15       16              14      NaN

In [45]:
# fetch all cse students of mumbai
branch_df3.loc['cse']['mumbai']

      average_package  students
2023                2       8.0
2024                5       0.0
2025                3       0.0
2026                0       8.0

In [47]:
# fetch cse students of delhi 2026 row
branch_df3.loc[('cse', 2026), 'delhi']

average_package    7
students           8
Name: (cse, 2026), dtype: int64