## Pandas

### Pandas Series -> it is like a column in a table. It is a 1D array holding data of any type

In [1]:
# importing pandas

import pandas as pd
import numpy as np

#### Series from lists

In [2]:
# string 

country =['India','Russia','USA','Japan']

# makeing series using .series() in pandas
# series has twwo things 1. index, 2. value
pd.Series(country)

0     India
1    Russia
2       USA
3     Japan
dtype: str

In [3]:
# integers

runs = [1,22,30,100,89,99,56,45,34,43]

# creating series
pd.Series(runs)

0      1
1     22
2     30
3    100
4     89
5     99
6     56
7     45
8     34
9     43
dtype: int64

#### custom indexing in series

In [4]:
marks = [90,23,57,34,23]
subject = ['Math','Hindi','English','Science','CS']

# creating series
# now make marks as value and subjects as index
# using index=(jise index banna cahte ho uska name)
pd.Series(marks,index=subject)

Math       90
Hindi      23
English    57
Science    34
CS         23
dtype: int64

#### Setting a name for series objects

In [5]:
# giving a name to this series
# using name parameter
pd.Series(marks,index=subject,name="Rohit's marks")

Math       90
Hindi      23
English    57
Science    34
CS         23
Name: Rohit's marks, dtype: int64

### Series from dictionary

In [6]:
# creating series from dictionary

# dictionary
sub_marks = {
    'math' : 100,
    'english' : 90,
    'science' : 100,
    'history' : 84,
}

In [7]:
# creating series from dictionary
marks_series = pd.Series(sub_marks,name="Mohit's marks")
marks_series

math       100
english     90
science    100
history     84
Name: Mohit's marks, dtype: int64

#### Series Attribute

In [8]:
# size attribute
# this tells us how many items are there in our series

# this will tell us about the size of our series
marks_series.size

4

In [9]:
# dtype
# this will tell us the type of data stored in series

marks_series.dtype

dtype('int64')

In [10]:
# name
# this will tell the name of our siries

marks_series.name

"Mohit's marks"

In [11]:
# is_unique
# this tells that all the items in a series are unique or not 
marks_series.is_unique

False

In [12]:
# index
# this will display all the index value in series

marks_series.index

Index(['math', 'english', 'science', 'history'], dtype='str')

In [13]:
# values
# this gives index object
# this will display all the value present in series

marks_series.values

array([100,  90, 100,  84])

## Series using read_csv

In [31]:
# importing subs.csv
df = pd.read_csv('data/subs.csv')


# creating series
df = df['Subscribers gained']
type(df)

pandas.Series

In [42]:
# reading data from csv file 

# reading kohli_ipl.csv data
kohli_runs = pd.read_csv('data/kohli_ipl.csv')
kohli_runs

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [45]:
# converting kohli_ipl.csv into series 
kohli_series = kohli_runs['runs']
kohli_series

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

In [59]:
# working with bollywood.csv

# reading bollywood.csv
bolly_data = pd.read_csv('data/bollywood.csv')
bolly_data

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [60]:
# making series of movie column
bolly_series = bolly_data['movie']
bolly_series

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1495                  Hum Tumhare Hain Sanam
1496                     Aankhen (2002 film)
1497                         Saathiya (film)
1498                          Company (film)
1499                    Awara Paagal Deewana
Name: movie, Length: 1500, dtype: str

In [61]:
# making series of lead column
bolly_lead_series = bolly_data['lead']
bolly_lead_series

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1495      Shah Rukh Khan
1496    Amitabh Bachchan
1497        Vivek Oberoi
1498          Ajay Devgn
1499        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [63]:
# making lead column -> index 
bolly_data = pd.read_csv('data/bollywood.csv',index_col='lead')
bolly_data

                                                 movie
lead
Vicky Kaushal                 Uri: The Surgical Strike
Vicky Ahuja                              Battalion 609
Anupam Kher       The Accidental Prime Minister (film)
Emraan Hashmi                          Why Cheat India
Mona Ambegaonkar                       Evening Shadows
...                                                ...
Shah Rukh Khan                  Hum Tumhare Hain Sanam
Amitabh Bachchan                   Aankhen (2002 film)
Vivek Oberoi                           Saathiya (film)
Ajay Devgn                              Company (film)
Akshay Kumar                      Awara Paagal Deewana

[1500 rows x 1 columns]

In [64]:
# making movie column -> index 
bolly_data = pd.read_csv('data/bollywood.csv',index_col='movie')
bolly_data

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]