# Multi index series and Data Frame

In [1]:
import numpy as np
import pandas as pd

### Multi indexing and Hierarchical both are same

## Multi index Series

In [2]:
# multi index series

# using pd.MultiIndex.from_tuples()
index_val = [('cse',2023),('cse',2024),('cse',2025),('cse',2026),('cse_ai',2023),('cse_ai',2024),('cse_ai',2025),('cse_ai',2026)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([(   'cse', 2023),
            (   'cse', 2024),
            (   'cse', 2025),
            (   'cse', 2026),
            ('cse_ai', 2023),
            ('cse_ai', 2024),
            ('cse_ai', 2025),
            ('cse_ai', 2026)],
           )

In [3]:
# multi index series

# using pd.MultiIndex.from_tuples()
pd.MultiIndex.from_product([['cse','cse_ai'],[2021,2022,2023,2024,2025,2026]])

MultiIndex([(   'cse', 2021),
            (   'cse', 2022),
            (   'cse', 2023),
            (   'cse', 2024),
            (   'cse', 2025),
            (   'cse', 2026),
            ('cse_ai', 2021),
            ('cse_ai', 2022),
            ('cse_ai', 2023),
            ('cse_ai', 2024),
            ('cse_ai', 2025),
            ('cse_ai', 2026)],
           )

In [4]:
 # creating series from multi index object
s = pd.Series([1,2,3,4,5,6,7,8],index=multiindex)
s

cse     2023    1
        2024    2
        2025    3
        2026    4
cse_ai  2023    5
        2024    6
        2025    7
        2026    8
dtype: int64

In [5]:
# fetch 4
print(s[('cse',2026)])

4

In [6]:
# fetch all cse_ai 
s['cse_ai']

2023    5
2024    6
2025    7
2026    8
dtype: int64

In [7]:
# unstack -> using unstack we can convert multi index series into a data frame
temp = s.unstack()
temp

        2023  2024  2025  2026
cse        1     2     3     4
cse_ai     5     6     7     8

In [8]:
# stack -> using stack we can convert a data frame into a series
# temp is a data frame
temp.stack()

cse     2023    1
        2024    2
        2025    3
        2026    4
cse_ai  2023    5
        2024    6
        2025    7
        2026    8
dtype: int64

## Multi index Series

In [9]:
branch_df1 = pd.DataFrame([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12],
    [13,14],
    [15,16]
], index=multiindex,columns=['average_package','students'])
branch_df1

             average_package  students
cse    2023                1         2
       2024                3         4
       2025                5         6
       2026                7         8
cse_ai 2023                9        10
       2024               11        12
       2025               13        14
       2026               15        16

In [10]:
# fetch all the cse_ai data 
branch_df1.loc['cse_ai']

      average_package  students
2023                9        10
2024               11        12
2025               13        14
2026               15        16

In [11]:
# multi index data frame from column perspective
branch_df2 = pd.DataFrame([
    [1,2,4,0],
    [3,4,0,9],
    [5,6,4,0],
    [7,8,0,3],
],index=[2023,2024,2025,2026],columns= pd.MultiIndex.from_product([['delhi','mumbai'],['average_package','students']])) # we did column based multi indexing

branch_df2

               delhi                   mumbai
     average_package students average_package students
2023               1        2               4        0
2024               3        4               0        9
2025               5        6               4        0
2026               7        8               0        3

In [12]:
# fetch mumbai's students average package
branch_df2['mumbai']['average_package']

2023    4
2024    0
2025    4
2026    0
Name: average_package, dtype: int64

In [13]:
# fetching row
# fetch 2026 row
branch_df2.loc[2026]

delhi   average_package    7
        students           8
mumbai  average_package    0
        students           3
Name: 2026, dtype: int64

In [14]:
# multi index data frame in terms of both rows and columns
branch_df3 = pd.DataFrame([
    [1,2,2,8],
    [3,4,5,0],
    [5,6,3,0],
    [7,8,0,8],
    [9,10,10,38],
    [11,12,28,9],
    [13,14,90],
    [15,16,14]
],
index=multiindex,columns=pd.MultiIndex.from_product([['delhi','mumbai'],['average_package','students']])
)
branch_df3 # this is a 4D data represented using 2d structure that is  data frame

                      delhi                   mumbai
            average_package students average_package students
cse    2023               1        2               2      8.0
       2024               3        4               5      0.0
       2025               5        6               3      0.0
       2026               7        8               0      8.0
cse_ai 2023               9       10              10     38.0
       2024              11       12              28      9.0
       2025              13       14              90      NaN
       2026              15       16              14      NaN

In [15]:
# fetch all cse students of mumbai
branch_df3.loc['cse']['mumbai']

      average_package  students
2023                2       8.0
2024                5       0.0
2025                3       0.0
2026                0       8.0

In [16]:
# fetch cse students of delhi 2026 row
branch_df3.loc[('cse', 2026), 'delhi']

average_package    7
students           8
Name: (cse, 2026), dtype: int64

## Stacking and Unstacking

### Unstacking -> it is the process of converting one level of a row index into columns

In [17]:
branch_df1.unstack()

       average_package                students
                  2023 2024 2025 2026     2023 2024 2025 2026
cse                  1    3    5    7        2    4    6    8
cse_ai               9   11   13   15       10   12   14   16

### Stacking -> it is the process of converting one level of a column index into rowa

In [18]:
branch_temp_df = branch_df1.unstack()
branch_temp_df.stack()

             average_package  students
cse    2023                1         2
       2024                3         4
       2025                5         6
       2026                7         8
cse_ai 2023                9        10
       2024               11        12
       2025               13        14
       2026               15        16

### Working with Multi index data frame

In [19]:
# head
branch_df3.head()

                      delhi                   mumbai
            average_package students average_package students
cse    2023               1        2               2      8.0
       2024               3        4               5      0.0
       2025               5        6               3      0.0
       2026               7        8               0      8.0
cse_ai 2023               9       10              10     38.0

In [20]:
# shape
branch_df3.shape

(8, 4)

In [21]:
# info
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2023)) to ('cse_ai', np.int64(2026))
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   (delhi, average_package)   8 non-null      int64
 1   (delhi, students)          8 non-null      int64
 2   (mumbai, average_package)  8 non-null      int64
 3   (mumbai, students)         6 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 820.0+ bytes

In [22]:
# duplicated 
branch_df3.duplicated()

cse     2023    False
        2024    False
        2025    False
        2026    False
cse_ai  2023    False
        2024    False
        2025    False
        2026    False
dtype: bool

In [23]:
# isnull
branch_df3.isnull()

                      delhi                   mumbai
            average_package students average_package students
cse    2023           False    False           False    False
       2024           False    False           False    False
       2025           False    False           False    False
       2026           False    False           False    False
cse_ai 2023           False    False           False    False
       2024           False    False           False    False
       2025           False    False           False     True
       2026           False    False           False     True

In [24]:
# Ectracting rows and columns

# 4D data frame (branch_df3)
branch_df3.loc[('cse',2026)]

delhi   average_package    7.0
        students           8.0
mumbai  average_package    0.0
        students           8.0
Name: (cse, 2026), dtype: float64

In [25]:
# Extract multiple row
# fetch 1st, 3rd, 5th row

 # using .loc()
branch_df3.loc[('cse',2023):('cse_ai',2024):2]

                      delhi                   mumbai
            average_package students average_package students
cse    2023               1        2               2      8.0
       2025               5        6               3      0.0
cse_ai 2023               9       10              10     38.0

In [26]:
# using .iloc()
branch_df3 .iloc[0:5:2]

                      delhi                   mumbai
            average_package students average_package students
cse    2023               1        2               2      8.0
       2025               5        6               3      0.0
cse_ai 2023               9       10              10     38.0

In [27]:
# Extracting columns

# fetch delhi students
branch_df3['delhi']['students']

cse     2023     2
        2024     4
        2025     6
        2026     8
cse_ai  2023    10
        2024    12
        2025    14
        2026    16
Name: students, dtype: int64

In [28]:
# Extracting multiple columns

# Fetch students of delhi and average package of mumbai
branch_df3 .iloc[:,1:3]

               delhi          mumbai
            students average_package
cse    2023        2               2
       2024        4               5
       2025        6               3
       2026        8               0
cse_ai 2023       10              10
       2024       12              28
       2025       14              90
       2026       16              14

In [29]:
# Extracting both 

# Extract cse 1st row, cse_ai 1st row and mumbai's agerage package and delhi's students
branch_df3.iloc[[0,1],[1,2]]

            delhi          mumbai
         students average_package
cse 2023        2               2
    2024        4               5

## Sorting

In [30]:
branch_df3.sort_index(ascending=False)

                      delhi                   mumbai
            average_package students average_package students
cse_ai 2026              15       16              14      NaN
       2025              13       14              90      NaN
       2024              11       12              28      9.0
       2023               9       10              10     38.0
cse    2026               7        8               0      8.0
       2025               5        6               3      0.0
       2024               3        4               5      0.0
       2023               1        2               2      8.0

In [31]:
# level 1 sorting
branch_df3.sort_index(level=1,ascending=[False])

                      delhi                   mumbai
            average_package students average_package students
cse    2026               7        8               0      8.0
cse_ai 2026              15       16              14      NaN
cse    2025               5        6               3      0.0
cse_ai 2025              13       14              90      NaN
cse    2024               3        4               5      0.0
cse_ai 2024              11       12              28      9.0
cse    2023               1        2               2      8.0
cse_ai 2023               9       10              10     38.0

In [32]:
# transpose -> Column will become rows and rows will become column
branch_df3.transpose()

                        cse                cse_ai
                       2023 2024 2025 2026   2023  2024  2025  2026
delhi  average_package  1.0  3.0  5.0  7.0    9.0  11.0  13.0  15.0
       students         2.0  4.0  6.0  8.0   10.0  12.0  14.0  16.0
mumbai average_package  2.0  5.0  3.0  0.0   10.0  28.0  90.0  14.0
       students         8.0  0.0  0.0  8.0   38.0   9.0   NaN   NaN

In [33]:
# swaplevel -> swaping the levels

# on rows
branch_df3.swaplevel()

                      delhi                   mumbai
            average_package students average_package students
2023 cse                  1        2               2      8.0
2024 cse                  3        4               5      0.0
2025 cse                  5        6               3      0.0
2026 cse                  7        8               0      8.0
2023 cse_ai               9       10              10     38.0
2024 cse_ai              11       12              28      9.0
2025 cse_ai              13       14              90      NaN
2026 cse_ai              15       16              14      NaN

In [34]:
# swaplevel -> swaping the levels

# on column
branch_df3.swaplevel(axis=1)

            average_package students average_package students
                      delhi    delhi          mumbai   mumbai
cse    2023               1        2               2      8.0
       2024               3        4               5      0.0
       2025               5        6               3      0.0
       2026               7        8               0      8.0
cse_ai 2023               9       10              10     38.0
       2024              11       12              28      9.0
       2025              13       14              90      NaN
       2026              15       16              14      NaN

## Long VS Wide data

#### Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes. (No. of columns more, rows less)

#### Long format is where, for each data point we have as many rows as the number of attributes and each row contains the value of a particular attribute for a given data point.(No of rows more, columns less)

In [35]:
# melt -> it converts wide data format into long data format
melt_df = pd.DataFrame({
    'cse':[140],
    'cse_ai':[200],
    'cse_ml':[70]
})

# performing melt in melt_df
melt_df.melt(var_name='branch',value_name='no. of students')

   branch  no. of students
0     cse              140
1  cse_ai              200
2  cse_ml               70

In [36]:
# next example
pd.DataFrame({
    'branch':['cse','cse_ai','cse_gen_ai','ece'],
    '2023':[100,210,130,213],
    '2024':[190,329,340,489],
    '2025':[290,870,652,832],
    '2026':[500,600,800,900]
} 
).melt(id_vars=['branch'],var_name='year',value_name='students') # iid_vars = columns you want to keep unchanged (as identifiers)

        branch  year  students
0          cse  2023       100
1       cse_ai  2023       210
2   cse_gen_ai  2023       130
3          ece  2023       213
4          cse  2024       190
5       cse_ai  2024       329
6   cse_gen_ai  2024       340
7          ece  2024       489
8          cse  2025       290
9       cse_ai  2025       870
10  cse_gen_ai  2025       652
11         ece  2025       832
12         cse  2026       500
13      cse_ai  2026       600
14  cse_gen_ai  2026       800
15         ece  2026       900

#### Melt using real world example (Working with covid data sets)

In [37]:
confirm = pd.read_csv('data/time_series_covid19_confirmed_global.csv')
confirm

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [38]:
death = pd.read_csv('data/time_series_covid19_deaths_global.csv')
death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [39]:
# convert these above data sets into a df which have 2 columns -> name,country,confirm cases, death cases

# using melt -> changing wide data into long data
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')


confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')

# merge
confirm.merge(death, on=['Province/State','Country/Region','Lat','Long','date'])[['Country/Region','date','num_cases','num_deaths']]

              Country/Region     date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]

#### Pivot table 
##### The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.

In [40]:
import seaborn as sns

In [41]:
df = pd.read_csv('data/tips.csv')
df

    total_bill   tip     sex smoker   day    time  size
0        16.99  1.01  Female     No   Sun  Dinner     2
1        10.34  1.66    Male    Yes   Sat  Dinner     3
2        21.01  3.50    Male     No   Fri  Dinner     3
3        23.68  3.31    Male    Yes  Thur   Lunch     2
4        24.59  3.61  Female     No   Sun   Lunch     4
5        12.43  1.80  Female     No   Fri   Lunch     2
6        18.29  2.71    Male    Yes   Sat  Dinner     4
7        15.77  2.00    Male     No   Sun  Dinner     2
8        27.28  4.00  Female    Yes   Sat  Dinner     5
9        22.76  3.00    Male     No  Thur   Lunch     2
10       17.92  2.50  Female     No   Fri  Dinner     2
11       19.65  3.00    Male    Yes   Sat  Dinner     3
12       14.50  2.00  Female     No  Thur   Lunch     2
13       28.17  4.50    Male    Yes   Sun  Dinner     6
14       11.80  1.50  Female     No   Fri   Lunch     2
15       20.27  3.25    Male    Yes   Sat  Dinner     4
16       13.37  2.00  Female     No  Thur   Lunch     2
17       25.56  3.80    Male    Yes   Sun  Dinner     4
18       18.64  2.80  Female     No   Fri  Dinner     3
19       29.85  5.00    Male    Yes   Sat  Dinner     6
20        9.60  1.40  Female     No  Thur   Lunch     1
21       26.88  4.20    Male    Yes   Sun  Dinner     5
22       15.42  2.10  Female     No   Fri   Lunch     2
23       19.81  3.00    Male    Yes   Sat  Dinner     3
24       22.67  3.50  Female     No   Sun  Dinner     3
25       13.81  2.00    Male     No  Thur   Lunch     2
26       17.51  2.60  Female    Yes   Fri  Dinner     2
27       30.14  5.20    Male    Yes   Sat  Dinner     6
28       21.79  3.25  Female     No   Sun  Dinner     3
29       16.40  2.20    Male     No  Thur   Lunch     2

In [42]:
# pivot table
df.pivot_table(index='sex',columns='smoker',values='total_bill')

smoker         No        Yes
sex
Female  16.643333  22.395000
Male    17.950000  22.967273

In [43]:
# aggr function

# total bill
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum')

smoker      No     Yes
sex
Female  199.72   44.79
Male     89.75  252.64

In [44]:
# multidimensional
df.pivot_table(index=['sex','smoker'],columns=['day','time'],values='total_bill')

day              Fri                   Sat        Sun              Thur
time          Dinner      Lunch     Dinner     Dinner  Lunch      Lunch
sex    smoker
Female No      18.28  13.216667        NaN  20.483333  24.59  12.490000
       Yes     17.51        NaN  27.280000        NaN    NaN        NaN
Male   No      21.01        NaN        NaN  15.770000    NaN  17.656667
       Yes       NaN        NaN  21.192857  26.870000    NaN  23.680000

In [45]:
# margins -> calculate the sum
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum',margins=True)

smoker      No     Yes     All
sex
Female  199.72   44.79  244.51
Male     89.75  252.64  342.39
All     289.47  297.43  586.90

In [46]:
# plotting graph
df = pd.read_csv('data/expense_data.csv')
df.head()

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0