# Some important Series Methods

In [2]:
import numpy as np
import pandas as pd

In [3]:
# subs data import
subs = pd.read_csv('data/subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [4]:
# importing ipl data
vk = pd.read_csv('data/kohli_ipl.csv')
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [5]:
# importig movies data
movies = pd.read_csv('data/movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

## Series methods

In [6]:
# astype -> change the data type
import sys
sys.getsizeof(vk)

3604

In [7]:
# change data type ( to int16
vk.astype('int16')

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [8]:
# clip 
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [19]:
# drop_duplicates
temp = pd.Series([1,2,3,2,4,5,4,7,6,5])
temp.drop_duplicates()

0    1
1    2
2    3
4    4
5    5
7    7
8    6
dtype: int64

In [10]:
# duplicated -> check is there any duplicated values or not
temp.duplicated().sum()

np.int64(3)

In [11]:
# size -> counts all the values included null

# creating a series 
temp2 = pd.Series([1,2,np.nan,3,2,4,5,np.nan,5,np.nan])
temp2.drop_duplicates()
temp2.size

10

In [12]:
# count -> it dosen't count null values
temp2.count()

np.int64(7)

In [13]:
# isnull -> check how many missing values in data
vk.isnull().sum()

match_no    0
runs        0
dtype: int64

In [14]:
# dropna -> remove all missing values
# it creates a new series
temp2.dropna()

0    1.0
1    2.0
3    3.0
4    2.0
5    4.0
6    5.0
8    5.0
dtype: float64

In [15]:
# fillna -> to fill the missing values
# it creates a new series
temp2.fillna(0)

0    1.0
1    2.0
2    0.0
3    3.0
4    2.0
5    4.0
6    5.0
7    0.0
8    5.0
9    0.0
dtype: float64

In [16]:
# isin -> check multiple things in data
vk[vk.isin([49,99])]

     match_no  runs
0         NaN   NaN
1         NaN   NaN
2         NaN   NaN
3         NaN   NaN
4         NaN   NaN
..        ...   ...
210       NaN   NaN
211       NaN   NaN
212       NaN   NaN
213       NaN   NaN
214       NaN   NaN

[215 rows x 2 columns]

In [17]:
    # apply -> helps to apply custom logic in series
subs['Subscribers gained'].apply(lambda x: 'good day' if x > subs['Subscribers gained'].mean() else 'bad day')

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: str

In [18]:
# copy 
# copy makes copy of the data so if we perform any operation into it the real data will remain unchanged
# when we use .head() it gives the view of the data and if we do any changes into it - it will affect the data
vk.head(2).copy()

   match_no  runs
0         1     1
1         2    23